### ISSUE TITLE
VLC Video Source Support?

### ISSUE THREAD

**Issue by N6UDP** [WarmUpTill/SceneSwitcher#51] opened 2020-10-17 22:09 UTC
Not sure how hard it would be to add support for the VLC Video Source but it would be great to have.  Some types of media work significantly better with the VLC source instead of the "Media source".

**Comment by WarmUpTill** [comment] 2020-10-18 01:09
Hi,
thanks for the suggestion.
This was also requested in the forums and I will add this in the next release.
You can find a build where it is already enabled here:
https://github.com/WarmUpTill/SceneSwitcher/runs/1269786247

But note there were reports of unexpected behavior with the VLC source which I still have to investigate.

**Comment by alforno** [comment] 2020-10-20 17:18
I love the UI changes but the VLC events are either not being caught or not being handled. I've tried all of the events (playing, stopped, ended...) and none of them will trigger a scene change for me.

**Comment by WarmUpTill** [comment] 2020-10-20 17:51
Thanks for the hint!

The main difference is that I am polling the state every x milliseconds while the Media Controls plugin connects to the OBS signals to get the state.

```
	signal_handler_t *sh = obs_source_get_signal_handler(source);
	signal_handler_connect(sh, "media_play", OBSMediaPlay, this);
	signal_handler_connect(sh, "media_pause", OBSMediaPause, this);
	signal_handler_connect(sh, "media_restart", OBSMediaPlay, this);
	signal_handler_connect(sh, "media_stopped", OBSMediaStopped, this);
	signal_handler_connect(sh, "media_started", OBSMediaStarted, this);
	signal_handler_connect(sh, "media_ended", OBSMediaStopped, this);
```

So while I might miss a stop stopped / ended event by polling the media controls will not as they are notified by OBS when it happens.
Using these signals will need some adjustments for the media source handling in scene switcher.
(I will probably settle for add flags to the media switch which are set by these signals and checking them every x milliseconds)

**Comment by alforno** [comment] 2020-10-20 17:54
> Thanks for the hint!
> So while I might miss a stop stopped / ended event by polling the media controls will not as they are notified by OBS when it happens.

Glad I could help and makes sense.

**Comment by WarmUpTill** [comment] 2020-10-20 19:01
Can you maybe just share the settings that were causing issues with the current implementation?
VLC Source (I assume directory) and Scene Switcher (which state?) would both be helpful in reproducing the problem / verifying possible solutions.

**Comment by alforno** [comment] 2020-10-21 13:08
**Scene switcher settings**
When _Music Playlist_ state is Stopped and _None 0ms_ switch to _Blank Scene_ using _Fade_

**VLC Playlist settings**
Name: Music Playlist
Loop Playlist: unchecked 
Shuffle Playlist: unchecked
Visibility behavior: _Pause when not visible, unpause when visible_
Paylist: contains three mp4 video files, not directories.
Network Caching (ms): 400
Audio Track: 1
Subtitles Enabled: unchecked
Subtitle Track: 1

**Comment by WarmUpTill** [comment] 2020-10-21 19:44
Thanks!

I can reproduce the problem quite easily and implemented the signal approach mention above, but ...

Strangely, it looks like both "media_stopped" and "media_ended" are sent whenever an entry in the VLC source playlist ends even if the end of the whole playlist is not reached yet.

I'm not sure what the best approach would be to proceed.
Should I ...
- ... handle both events, stopped and ended, as they arrive thus them being equal in this scenario
- ... ignore the "ended" signal and rely on it being checked via obs_source_media_get_state() thus "missing" it most of the time, so it could be used as a way to specify "end of playlist" reached
- ... the previous point, but reversed.

Do you have any preference?

I think the first way would be a rather unexpected behaviour for most users as they would expected them these states to behave differently.

The issue with the 2nd and 3rd approach is that it could in theory not be 100% reliable if obs_source_media_get_state() is called at the perfect moment to catch a "ended" or "stopped" event in the middle of a playlist.

**Comment by alforno** [comment] 2020-10-21 20:39
That's a tricky one and makes it seem that VLC source playlist is either not implemented correctly or the states are not taking into account a playlist, requiring an addition "playlist ended" state or something like that. I'm going to take a look at the VLC playlist code and see what I can find out.

**Comment by WarmUpTill** [comment] 2020-10-22 20:14
Let me know if you find anything - so far I have not :)
I am only of these media states defined in obs-source.h:
```
enum obs_media_state {
	OBS_MEDIA_STATE_NONE,
	OBS_MEDIA_STATE_PLAYING,
	OBS_MEDIA_STATE_OPENING,
	OBS_MEDIA_STATE_BUFFERING,
	OBS_MEDIA_STATE_PAUSED,
	OBS_MEDIA_STATE_STOPPED,
	OBS_MEDIA_STATE_ENDED,
	OBS_MEDIA_STATE_ERROR,
};
```
You can find a build of the plugin with the first approach here:
https://github.com/WarmUpTill/SceneSwitcher/pull/44/checks?check_run_id=1294688106
However, I am not sure how useful that will be.

**Comment by alforno** [comment] 2020-10-22 20:53
https://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__event.html#ga284c010ecde8abca7d3f262392f62fc6
I'm looking at those events trying to figure out which one means the entire playlist has finished playing. Once I find it, then I can see if the vlc playlist plugin is aware of it.

**Comment by alforno** [comment] 2020-10-22 21:27
https://github.com/obsproject/obs-studio/blob/master/plugins/vlc-video/vlc-video-source.c
In the function vlcs_create() several callbacks are setup, but none are setup for the playlist events.
What should be happening is that the vlc-video plugin should be registering a callback for a MediaListPlayer event like libvlc_MediaListPlayerStopped. That might work for LIST_STOPPED, but not for LIST_ENDED.

Someone here commented that it might be easier to implement VLC list playback differently.
https://stackoverflow.com/questions/53511780/how-can-i-tell-the-progress-of-a-vlc-medialistplayer

**Comment by WarmUpTill** [comment] 2020-10-23 00:39
Thank you very much for your investigation!

I guess for now I could leave the implementation as is until this is resolved.

But one workaround, that I can think of, is that I could minimize the chance of the drawback of approach 2 and 3 - it not being 100% reliable - by requiring two consecutive matches for stopped / ended using obs_source_media_get_state().
This could only be a problem is someone selects a item for the playlist that happens to be exactly the length of the chosen interval for the scene switcher checks and thus if the scene switcher just happens to call obs_source_media_get_state() at the perfect moment twice in a row, which should be extremely unlikely.
The downside would be that the scene switcher will react one interval later for this event type in the case of the VLC source than it should, which should be acceptable most of the time (if not always).

What do you think?

**Comment by alforno** [comment] 2020-10-23 18:00
You're welcome, thanks for the great plugin. Your workaround sounds reasonable to me.

**Comment by WarmUpTill** [comment] 2020-10-24 13:48
You can find a recent build with this workaround here:
https://github.com/WarmUpTill/SceneSwitcher/runs/1302131979

I chose the state "ended" to be used to specify the "end of the playlist" state for the workaround.
In my (limited) testing it worked quite well.


I also noticed that the VLC source do not seem to behave the same way every time.
Some times on playlist item change or the end of the playlist both stopped and ended are sent and other times just ended is.
(When stopping the playback just stopped is signaled - so this works as expected)
I am starting to think that his might be an issue with my setup.

**Comment by WarmUpTill** [comment] 2020-11-01 10:23
Please note that I might have introduced a new bug during my UI rework, which is also present in the builds I shared above.
(See https://github.com/WarmUpTill/SceneSwitcher/issues/53)

**Comment by WarmUpTill** [comment] 2020-11-30 22:00
I will close this as VLC sources are supported in the newest release (even though for now workarounds are used to support it).

**Closed by WarmUpTill** 2020-11-30 22:00 UTC
