### ISSUE TITLE
Causes OBS 27.2.0-beta4 to crash

### ISSUE THREAD

**Issue by GibStorm** [WarmUpTill/SceneSwitcher#401] opened 2022-01-29 12:00 UTC
**Describe the bug**
The plugin causes a crash with the OBS 27.2.0-beta4 version, and thus probably also the upcoming final release. The crash happens when you try to close OBS.

**To Reproduce**
1. Run OBS 27.2.0-beta4
2. When closing OBS, it will crash.
3. The crashlog clearly states advanced scene switcher as the cause.

**Expected behavior**
No error should occur when closing OBS

**Logs**
https://obsproject.com/logs/qMwdKjEKyUKxRUJP

**Version information**
 - OS: Windows 11
 - OBS Version: 27.2.0-beta4
 - Plugin Version: 1.17.1

**Additional context**
None

**Comment by WarmUpTill** [comment] 2022-01-29 15:16
Thanks for reporting the issue!
Should already be fixed with d1331a60b9bed3e8325f37246747f384e8f406dd, but was not officially released yet.

Can you test, if the issue is resolved with this build?
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/1766068606

I will make a new release in a few hours mainly for this crash fix.
So another confirmation that the issue is gone would be much appreciated! :)

**Comment by WarmUpTill** [comment] 2022-01-30 00:34
New release was published so I will close this for now.
But please let me know if the issue should not be resolved on your end.

**Closed by WarmUpTill** 2022-01-30 00:34 UTC

**Comment by GibStorm** [comment] 2022-01-30 11:16
Works now, thanks!
