### ISSUE TITLE
OCR does not seem to detect any text

### ISSUE THREAD

**Issue by nacalai** [WarmUpTill/SceneSwitcher#711] opened 2023-04-02 00:31 UTC
Hey there. Just trying out your new release. Without knowing too much about the inner works of OCR, I would assume it to be able to pick up a regular in game chat. It finds no text. I then tried making it detect text in notepad in a very large font. No match. Perhaps something's not right?

Edit: I had not started ASS, apparently. If I leave the text field empty, it does trigger my notification. So, I guess it does detect *some* text. But, when my notepad with really big font say "hello" and I enter "hello" into the text field, it does not find it.

Edit2: OBS will simply close without warning if I fiddle too much with the settings. I'll see if I'm able to upload a log at a later time. Perhaps you want it as a separate issue..?

**Comment by WarmUpTill** [comment] 2023-04-02 14:03
An essential aspect of the process is to select the appropriate text color that allows for differentiation between the text and the background. Typically, the text's color is the optimal choice, but it may not always be the case.

Choosing the correct `text type` selection is also crucial, and the descriptions of the available options should hopefully be self-explanatory.

Moreover, detecting larger texts will in general be easier than smaller ones.

It is noteworthy that the text detection model was trained using the English language. Therefore, for example, if you aim to detect French words, the model may encounter difficulties. Nonetheless, you can replace the model under `obs-studio\data\obs-plugins\advanced-scene-switcher\res\ocr` with the relevant one for a particular language, but keeping the `eng.traineddata` name. You can find the model data for other languages here: https://github.com/tesseract-ocr/tessdata.

Improving the outcomes could be possible by restricting the search area to the relevant parts of the video source.

Finally, you can check the detected text by clicking on the "Show match" button. 
This is an example of what is being detected using your GitHub issue prompt captured by a `Window Capture` source.

![OCRExample](https://user-images.githubusercontent.com/19472752/229357422-d211ab1c-9cf7-4e92-882a-22339db3b6d7.PNG)

Let me know if you have any questions! :)

**Comment by WarmUpTill** [comment] 2023-04-02 17:20
>OBS will simply close without warning if I fiddle too much with the settings. I'll see if I'm able to upload a log at a later time. Perhaps you want it as a separate issue..?

I _think_ I found the issue that might be causing this.
Can you check if the problem is resolved in this build?

https://github.com/WarmUpTill/SceneSwitcher/actions/runs/4589889565

**Closed** 2023-04-11 10:55 UTC
