### ISSUE TITLE
Source Media switching

### ISSUE THREAD

**Issue by exeldro** [WarmUpTill/SceneSwitcher#16] opened 2020-04-01 06:28 UTC
In OBS version 25 source media functions are added to request the state of media.
- obs_source_media_get_state
- obs_source_media_get_time
- obs_source_media_get_duration

This works for the media and the vlc source

I want to be able to automatically start a transition 1 second before the end of a video.

**Comment by Wiethoofd** [comment] 2020-04-26 15:31
I see this got added in #18, including the remaining/elapsed duration for your video source.

The only thing in 'Switch to' dropdown that is missing is _Previous Scene_, you can currently only select a predetermined scene, not simply return to the previous one.

**Comment by WarmUpTill** [comment] 2020-04-27 18:32
I added this with 4ed12db12b6a55d64324a316185e9f18c9cca095.
Is this working for you as expected?

The latest release was updated to include this change for the Windows 64 bit and 32 bit dlls.
I don't know when I will get around to building it for the other platforms yet.

**Comment by Wiethoofd** [comment] 2020-05-14 19:10
Switching to the previous selected scene works.

However, the Media switch itself doesn't override any set 'transition overrides' on any scene when switching, only works with no overrides defined.

----

Also wouldn't mind being able to 'edit' a configured switch by double clicking on it to repopulate the fields above the list of configured transitions.

And possibly a reorder option, in case they actually do take priority, similar to the 'switching methods priority sort' under General.

**Comment by WarmUpTill** [comment] 2020-06-16 18:34
The option for easier edit was added with the last release.
I now added the option to reorder the entries with eeefd8279f5bce2d39f2cb9f8b1cfba4b16adf1b.

Can you clarify what the issue is here?
Are you referring to the transition tab or the transition set on the media tab?
>However, the Media switch itself doesn't override any set 'transition overrides' on any scene when switching, only works with no overrides defined.

Or was this maybe also resolved with the bugfixes of the latest release?

**Comment by Wiethoofd** [comment] 2020-06-16 18:55
On a few scenes I have a 'Transition override' set to play a stinger/transtion, which is different from the one I define in the Media tab transition (I don't use any other ones, so can't confirm if they are showing the same behaviour).

e.g. `Switch to Previous Scene using Fade if MyVideoFile state is ended`
I would expect this to _fade_ to the previous scene, overruling any transition overrides already in place, taking a higher priority, similar to how 'Quick Transitions' have a higher priority than defined scene specific transition overrides. However it is using the regular 'Transition' action when switching to the _previous scene_ at the moment; with the latest 1.61 release.

**Comment by WarmUpTill** [comment] 2020-06-17 17:28
Ah I understand now. Thanks for the explanation!
I am not sure if it is possible for me to overrule the transition override.
I will investigate.

**Comment by WarmUpTill** [comment] 2020-06-17 20:21
I added the option to override transition overrides with 340cb55.
Automated build artifacts should be available in a few minutes here:
https://github.com/WarmUpTill/SceneSwitcher/runs/781940637

Please let me know if it is working as expected.

**Comment by Wiethoofd** [comment] 2020-06-17 21:11
Can confirm with the checkbox ticked under 'Transition' the Media tab transition override takes priority over the scene defined transition override.

Would personally make more sense to see the option on the General tab, but can at least confirm that having it ticked makes transitions behave as I initially (mistakenly) expected.

**Closed** 2020-06-17 21:40 UTC
