### ISSUE TITLE
There is a bug in 1.8.1.

### ISSUE THREAD

**Issue by iesvme** [WarmUpTill/SceneSwitcher#81] opened 2020-12-13 14:16 UTC
It can only set correctly when checking two times "Automatically stop streaming/recording on scene"

**Comment by WarmUpTill** [comment] 2020-12-13 15:54
First of all thanks for reporting that there is a problem.

Sorry, I do not quite understand.
Are you referring to a UI issue or is there an issue with the functionality of that option?

**Comment by iesvme** [comment] 2020-12-13 17:06
sorry, I mean that if you only check it once and exit, then you will find that the option is not selected.  you should need to re-select it. by doing so, it just work.

**Comment by WarmUpTill** [comment] 2020-12-14 20:08
So you are referring to the checkbox on the general tab, aren't you?
If you are then I cannot seem to reproduce the issue.

Could it be that no valid scene was selected or the scene which was selected was deleted?
This would cause the option to be unchecked again.

**Comment by WarmUpTill** [comment] 2020-12-21 22:06
I will close this for now under the assumption that one of the above scenarios happened on your end causing the checkbox to be unselected again.

If I misunderstood something feel free to reopen!

Thanks again for reporting issues - even if this one should have been intended behaviour - it is always appreciated!

**Closed by WarmUpTill** 2020-12-21 22:06 UTC
