### ISSUE TITLE
MacOs: Deleting last macro causes OBS to crash

### ISSUE THREAD

**Issue by Lumbra74** [WarmUpTill/SceneSwitcher#472] opened 2022-06-08 15:21 UTC
Deleting last macro causes OBS to crash

1. Go to 'Macros'
2. Create a new macro
3. delete the macro

Version information:
OS: macOS 12.4
OBS Version 27.2.2
Plugin Version 1.17.

**Comment by WarmUpTill** [comment] 2022-06-08 16:54
Can you please share the settings you are using to reproduce the issue?
They can be exported to a file on the General tab.

**Comment by Lumbra74** [comment] 2022-06-11 11:36
[Settings](https://github.com/WarmUpTill/SceneSwitcher/files/8883757/adv-ss-Zoom-2022.06.11.13.34.42.txt)

With these settings, the crash occurs. The corresponding scene collection was duplicated, from an existing one.

**Comment by WarmUpTill** [comment] 2022-06-11 18:52
Thanks for sharing the settings!
So far I was not able to recreate the issue, unfortunately.

Do you also happen to have a crash log?

**Comment by WarmUpTill** [comment] 2022-06-12 13:06
I think I finally found the root cause of the issue:

A crash can occur if the last macro was deleted **and** the highlighting of macro segments was enabled due to the macro the segments already being deleted while the widgets representing these segments were not.
As soon as these remaining widgets check whether or not the highlight should be shown they will try to access already freed memory addresses and thus this would cause the crash.

Should be fixed with the linked PR.

A build with this fix will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/2483558398

Let me know if that solves the issue also on your end! :)

**Closed** 2022-06-12 13:45 UTC
