### ISSUE TITLE
Paste as else action doesn't work

### ISSUE THREAD

**Issue by Destroy666x** [WarmUpTill/SceneSwitcher#1209] opened 2024-09-21 22:45 UTC
### Operating System Info

Windows 10

### OBS Studio Version

30.2.3

### Advanced Scene Switcher Version

cleanup branch

### Expected Behavior

Paste copied action as else action

### Current Behavior

It pastes as regular action

### Steps to Reproduce

1. Copy regular action
2. Try to paste as else action

**Comment by WarmUpTill** [comment] 2024-09-22 05:44
Hm ... I am not able to reproduce it on my end.
Can you share the macro you are using to reproduce the issue?

**Comment by Destroy666x** [comment] 2024-09-22 06:43
Oh ye, it happens inconsistently. 3 macros were affected, 2 of which I deleted, 1 that stayed is this and it still happens there:
![2024 09 22 08 41 26 121 Advanced_Scene_Switcher_-_1 27 2-132-g38d5ac96](https://github.com/user-attachments/assets/9fe68eac-2091-42ba-a28f-5000fc00f134)

```
AAAcLnic7Vnhbts2EH4Vghiwtoszy0671f9Sx2mNxY1nuVmHtSgY6SwRkUiBpJK4Wd59R0qyZTuO7TbrsCIGElgn3nfHu+/uGOaGpixQUtPOXzdUsBRoh45lruxXYUgqQyAg2HkCId2jkZJ5RjsTlmjYoxnLNdSeFEsSSGjHqByfpejGTERQPesLnvWuITgVvmHKzPS0kdlhYLgUuj95K82RFHNQNODHUpkuV0HOTe+SJTmzaytUXNDNESLtShFy+6YbQ3DRFwYULp4BBfcuuqEWGGpfmvutl0ufPWqmmX11i2YFxx009+glKO3c8VAayuDCB2O4iLTFUhBxjTZmXsRMj3LxKjdmvgOUDW0gV6QYJpPrE3YO823EPIoT/DH9yWwveqzyecRUhT+Ga3SRoj1apmpB7mxSu5PVd+8KGb4NFowUHpWL5vYJU0Cs2/sLGsfWoftUnMdWx8atH+KCw6Mz32+s599CtB1xC+bMgP0s4QYjPpSaFzRBWmeW3m3v5e1e7fvHEqCHPhQg63W9g4OZrnfQtrpVat9IcwFTvVgThRD1P87iWxcZGUUJDJfF88g5yxoiG4I6nwKZJCzTGIpafRT0X6RJUJfRwZQk7isGjdswXzLFbUgxoomMeOCYHObKVdZAhnzCLWlvqOEpfEK/tFGMi4LxGqyj+u6iaW4qEhRX1t8udxu0DL15rstlrXJdX6AVHhInT86BaEjAJY7aJqLOCh+oh48iT89qLs0i67zB1ME1MmbCI+t7wa56GzO81jhkVqakeWvzzoJvnaGK/WVjWIregAubM2a5qAeYJD8AAV8RvsGANIiZV6DE5CVsuimoZSz64TXtNDx8zs99ozAsZbNv1kX8M8wzMWS26BCF7j+jpWzATBA7LFw14SIcWelu2SoU0aLlGPYf3BSxEmcjS1gAi+9KIbniJqZbs6ScdXWzKTNx7zpToAvS0yfEIz+RFnlG2uQp+Zkc0Bothkqm2XwacpHlppLRQ4SIBHHlZX2sktopEPpusfU6lklYmzN85QVtNMCOO2Jwu42G49UlV1LYrJ0tcuqd3xsNR6fH/ZOe5YYllD8ji+0KRYXvVecFy1oDaYYwC695RQZH6eX27XD7qNcXYZHbsot49R4SclUZbjqeIn9OQESYo1rfqWtkLAxxER4+0Jt2C4nKNIyr1/9q1Wosm+COmi3ld4RuZEk3JVhLBn2yQKzcrVeplY5Wx4ObwpRj6/TTeSHFOIEOFM8KXXoiWUgKbOecpcMATCzDIox14CVIvQI2YNc8zdMST5MneG56Sh3RRc6SEqbqHy/oF5Fhlg3q7HPLVctfOxOK8TSXnSpH6cdsfl/ZxOkKs8PY9z5hcbzkCVOP4/VxvD6O1/+gIS/3zf9LQ25+24bstlbx1/bkj1Z6WRPMb41AG6/VtpRml2UXL6EnLE9MtQNqWVLpjP0xNoQgHko0r0dwxVToLgt2QuHBBaitgLy9itRUx/IqxaRBKgW4D7myTT4k72zj1rqLULYrcDGRKu2QD/QNy7IpecWViUOk1QjEZ/mhiOjOzqER9yfWLg7eb+kP7L7yyneWjsAUdX0ExXSp22itwLQXPFZMFDcgR+WVwEb9Vl3fzcevd6PL0uP3W3vgNbcJuuvoO3FrkGse+DwBEcB2m3h+hyPbMPqHmxVbt+Rvcpd4Ietw7ks0Yl6DfJ0jbdUAf7FomVjblNBxLo6xQerdK3B2X9DF0QqGG6m8IvAb49XcBNR6KCDv7Wq9rcLgXJ/iIPc2urULWutuNHcQwwGw5Q7XoSzcm63pJs37m8faU+4auDWH2I0Ue40P99CsZuHkdNTrkHEMCtxtMUKjjwaSKRGSnOeRxs5M0I8WHpcJXAeQGeJnHIdXYmcdYSIkh+LH35gAHe9vcK5oFXYAux6xewUsAaxp77uBDKQ9KEmp8MTFDLx/SLA/v7DAh1IXtN2GILV7xAz1GqlV3IGIli3uiLJTy64jFPXXS+RYZicw2bH534n0SuKhMB3Z/8I8GNoDuYab3Nav2V327znkxdGudmik3n7rl/1Ww2u3GlH71/A5C16+oLf/APOZrqs=```

**Comment by WarmUpTill** [comment] 2024-09-23 19:11
Thanks! Found the issue:

Instead of checking the cursor position at the time of the paste, it needed to be checked at the time of the context menu creation to ensure the segment gets pasted into the correct section.
Should be fixed with https://github.com/WarmUpTill/SceneSwitcher/pull/1184/commits/086f31e4e092146a449e9e5e635b59a9bafb5bb0.

**Closed** 2024-09-23 20:52 UTC
