### ISSUE TITLE
Idle only resets on keyboard/mouse movement, not after firing

### ISSUE THREAD

**Issue by MikeFarrington** [WarmUpTill/SceneSwitcher#109] opened 2021-01-29 20:25 UTC
After the Idle scene switch happens, it will not happen again until X seconds after another keyboard or mouse movement is detected.  If you walk away, it'll only ever fire once.

**Comment by WarmUpTill** [comment] 2021-01-29 20:33
This is intended behavior and was requested to be changed three years ago, due to it causing scenes continuously switching back and forth, if "previous scene" was selected as a target. (https://github.com/WarmUpTill/SceneSwitcher/commit/78fa18f22a93ff2a9c4d169a346c679cf4b7ffb0)

What would your use-case be where it is required to continuously switch to the same scene?

**Comment by MikeFarrington** [comment] 2021-01-29 20:38
Every 5 minutes, I like to throw up a "Thank you for watching" scene with our logo and some other information.  This runs unattended (which is why this tool is so incredibly useful).  

Perhaps there could be an option checkbox for "Auto-Repeat When No Input Detected"?

**Comment by MikeFarrington** [comment] 2021-01-29 20:40
The commit you referenced, if I'm not mistaken, looks like it would prevent rapid continuous switching after the timer was reached.  What I'm looking for is it to fire at 5min, 10min, 15min and so on (when set to 300s).

**Comment by WarmUpTill** [comment] 2021-01-29 20:48
So you want the "idle timer" to reset every time it reaches its target?

I don't know your complete setup, but could the same not be achieved by using scene sequences or the option to switch to a specified scene after the specified amount of time of no matches?

While your suggestion could be implemented, I am not sure if this would be very intuitive for the scene switcher to behave this way by default.
"Auto-Repeat When No Input Detected" would probably interpreted as the way the plugin would behave if reverting 78fa18f.
Do you have another suggestion to name this behavior?

**Comment by MikeFarrington** [comment] 2021-01-29 21:40
Using the Sequence tab, I'm just cross-fading between three scenes, continuously, with about 10 seconds spent on each scene.  

My Sequence:
Scene1 -> Scene2 (10s)
Scene2 -> Scene3 (10s)
Scene3 -> Scene1 (10s)
SceneThankYou -> Scene1 (10s)

Then, the 4th sequence is my "Thank You For Watching", which sticks around for 10 seconds before going back to Scene1.  I was trying to use the Idle timer to have that ThankYou scene kick in every 5 minutes.  I'm rather new to the switcher, so if there's a better solution that I'm not seeing, please let me know.

Another title for the checkbox could be "Restart Input Timer After Switching Scenes"?

I suppose another option could be to replace "of keyboard or mouse inputs" with a pulldown, the first one being blank or "of time elapsed"?  It could allow for expansion, for example "After 90s of no motion detected switch scene to X" (As cool as that would be though, I imagine motion detection is way beyond the scope of your project).  Just throwing that out there as another time-based thing that could justify a pulldown.

Idle seemed like the obvious choice for this.  Honestly, I didn't really know what that "If no switch condition is met for xs" was for.  It's possible it could serve this purpose.  I just tested it now, and indeed it does serve my needs.

**Comment by WarmUpTill** [comment] 2021-01-30 02:32
I think a feature I just implemented might be what you are looking for.
This hasn't been released yet, so you will have to download it from one of the automated builds - e.g. here:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/515851486

In this build you will find an additional tab named "Scene Group".

A scene group is a collection of scenes, which can be selected as a target for the various switching methods of the plug-in.
For your use-case you would have to add a new Scene Group, which is configured the following way.
```
Advance to next scene in list after "1" matches.
[x] Restart from beginning if end of List is reached.

List of scenes:
Scene1
Scene1
Scene1
... (repeat however many times you like)
Scene1
SceneThankYou
```
Your sequence tab would then contain these settings:
```
Scene1 -> Scene2 (10s)
Scene2 -> Scene3 (10s)
Scene3 -> Scene Group 1 (10s)
SceneThankYou -> Scene1 (10s)
```

This entry of the sequence `Scene3 -> Scene Group 1 (10s)` would then switch to Scene1 for the amount of times you added it to the Scene Group's List and finally switch SceneThankYou.
As `[x] Restart from beginning if end of List is reached.` was checked the next time around the Scene Group is selected as a target it will start switching to Scene1 once again.

Would this work for you?

**Comment by MikeFarrington** [comment] 2021-01-30 14:56
Thanks, I'll give it a whirl sometime this weekend.

**Comment by WarmUpTill** [comment] 2021-02-05 22:48
Just FYI: I now released an official version which includes this new tab.
Were you already able to give this a try?

**Comment by WarmUpTill** [comment] 2021-02-17 19:48
I will close this for now - feel free to reopen if you run into any issues with the proposed solution! :)

**Closed by WarmUpTill** 2021-02-17 19:48 UTC
