### ISSUE TITLE
Advance Scene Switch (TIME) Losing Entries In Programming

### ISSUE THREAD

**Issue by CoreyRosen** [WarmUpTill/SceneSwitcher#784] opened 2023-07-03 05:10 UTC
**Describe the bug**
When I am entering a lot of entries into the Advanced Scene Switcher TIME Tab, it starts to glitch after I get to a certain amount. I am not sure what that amount is, but it prevents me from programming my schedule for more than a day or two.

**To Reproduce**
1. Make entries into the Time Tab in Advanced Scene Switcher.
2. Keep making entries. (ABOUT 250)
3. Close the Advance Scene Switcher window after you have a lot of entries.
4. When you reopen it, if there are no issues, keep making entries. (ABOUT 250)
5. Close the window again and reopen it.
6. Eventually the bottom of the Time Tab of the Advanced Scene Switcher will corrupt and not be what was entered.

**Expected behavior**
I would like to keep making entries and not have them corrupt.

**Logs**
The log for this issue seems to be glitchy as well. Shows starting at the top of the hour say that are starting at 15 after the hour in the log.

**Version information**
 - Windows 11
 - OBS 29.1.3
 - Advanced Scene Switcher 1.22.1

**Additional context**

**Comment by WarmUpTill** [comment] 2023-07-03 18:35
To be honest I am not sure what could be causing this.
Can you please share an export of your settings (even if they are not corrupted yet)?

https://github.com/WarmUpTill/SceneSwitcher/wiki/Saving-and-loading-settings

Maybe I can spot an issue.
I _assume_ it would be better to translate those to macros.

**Comment by CoreyRosen** [comment] 2023-07-03 18:55
Im not sure how to translate them to Macros... here is the settings file.
At this point, if I want to add more scene switches in the Time Tab, I
would need to erase over ones I have already made. This only gives me about
two or three days of programming. Before I upgraded OBS, I was able to
program in almost a whole week. Now I feel limited in what I can do. Please
help me fix this so we can get our network back up and running like it was.

**Comment by WarmUpTill** [comment] 2023-07-03 19:49
Seems like the attachment was lost.
Can you update your comment and attach it once again please?

**Comment by CoreyRosen** [comment] 2023-07-07 16:55
Hello there, I havent heard from you since I sent the file over. I will
send again just in case. If you do not receive it, is there another email I
can send it to?

**Comment by WarmUpTill** [comment] 2023-07-07 17:15
Unfortunately I think you need to attach it on the GitHub website otherwise it will simply be discarded.

**Comment by CoreyRosen** [comment] 2023-07-07 17:32
[Untitled.txt](https://github.com/WarmUpTill/SceneSwitcher/files/11984425/Untitled.txt)
Had to change the file to a TXT. It is a .JSON file. I hope you can help me... I think the maximum entries is around 200-250, but that is only enough entries for me to program a couple of days or less of content. I believe the previous Advanced Scene Switcher had around 500 entries before it started to do the same thing. 500 I could work with, but this is really a problem.

**Comment by WarmUpTill** [comment] 2023-07-07 19:22
While the file you attached is a vaild config file it is pretty much empty.
Are you sure you have attached the correct one? (Are you maybe in a scene collection different to your usual one?)

**Comment by CoreyRosen** [comment] 2023-07-07 19:26
I followed the instructions you left on how to get that file. Can you
please send instructions for how to get the current scene switcher time
profile in a file format I can send to you?

**Comment by CoreyRosen** [comment] 2023-07-08 18:26
Still waiting for a reply on above.

**Comment by WarmUpTill** [comment] 2023-07-08 19:11
The file _format_ of the file you previously attached is the correct one.
The file itself is just almost empty - meaning nothing is configured for the advanced scene switcher at all.

You need to export the settings of the advanced scene switcher on the OBS instance and scene collection that is causing the issue you have described.
I cannot really give more information here as I do not know how you have installed and set up your OBS.

**Comment by CoreyRosen** [comment] 2023-07-08 19:21
I hope this is the document you are looking for... this problem is crippling our network...
[Uploading adv-ss-PBMTV_1080_2.3 2-2023.07.08.12.16.55.txt…]()

**Comment by WarmUpTill** [comment] 2023-07-08 20:39
The link to the file is not valid :(
It does not point to any file and instead just links to the GitHub issue page of this issue.

**Comment by CoreyRosen** [comment] 2023-07-08 21:01
[adv-ss-PBMTV_1080_2.3 2-2023.07.08.12.16.55.txt](https://github.com/WarmUpTill/SceneSwitcher/files/11992397/adv-ss-PBMTV_1080_2.3.2-2023.07.08.12.16.55.txt)
Lets see if that works

**Comment by WarmUpTill** [comment] 2023-07-08 22:12
Yes, that worked - I now have access to the settings.

However, unfortunately I was not able to reproduce the problem.
Even after quadrupling the amount of entries (tried up to 816 entries in total) the saving and loading and addition of new entries still worked as expected.

Could it be that maybe that OBS is failing to save the scene collection data?
I can only speculate here, but maybe the folder where this data is stored is read-only for some reason?

---

Regarding the conversion of your settings to macros I wrote a small python script
It produced the following output, which you can import on the General tab.
[output.txt](https://github.com/WarmUpTill/SceneSwitcher/files/11992491/output.txt)

![Macro](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/ba8b98c3-06a0-4d6b-8530-104233a9554e)

Note that it only converts the "Time" tab settings - all other settings will be set to default if you import the file.

```python
import json

day_name = {
    0: "Any day",
    1: "Monday",
    2: "Tuesday",
    3: "Wednesday",
    4: "Thursday",
    5: "Friday",
    6: "Saturday",
    7: "Sunday",
}


def convert_json_format(original_json):
    new_json = {
        "name": f"{day_name[original_json['trigger']]} {original_json['time']} - {original_json['target']}",
        "conditions": [
            {
                "collapsed": False,
                "id": "date",
                "logic": 0,
                "dayOfWeek": original_json['trigger'],
                "condition": 0,
                "dateTime": f"Sat Jul 8 {original_json['time']} 2023",
                "dateTime2": f"Sat Jul 8 {original_json['time']} 2023",
                "ignoreDate": False,
                "ignoreTime": False,
                "repeat": False,
                "updateOnRepeat": True,
                "duration": {
                    "value": {
                        "value": 0.0,
                        "type": 0
                    },
                    "unit": 0,
                    "version": 1
                },
                "dayOfWeekCheck": True,
                "pattern": ".... .. .. .. .. .."
            }
        ],
        "actions": [
            {
                "collapsed": False,
                "id": "scene_switch",
                "sceneSelection": {
                    "type": 0,
                    "name": original_json['target']
                },
                "transitionType": 0,
                "transition": original_json['transition'],
                "duration": {
                    "value": {
                        "value": 0.0,
                        "type": 0
                    },
                    "unit": 0,
                    "version": 1
                },
                "blockUntilTransitionDone": True
            }
        ]
    }

    return new_json


if __name__ == '__main__':
    with open("input.json", "r") as input, open("output.json", "w") as output:
        original_json = json.load(input)
        result = json.loads('{}')
        result["macros"] = []
        for ts in original_json["timeSwitches"]:
            result["macros"].append(convert_json_format(ts))
        new_json_str = json.dumps(result, indent=4)
        output.write(new_json_str)

```

**Comment by CoreyRosen** [comment] 2023-07-08 23:50
Nope, thats not it because it saves every time I use it. The problem is,
when I reopen the Advanced Scene Switcher, with what appears to be 250+
entries, after closing it to save the data, it opens with corrupted data.
If it wasn't saving, the scene switcher would open with the previously
saved data. So, you are scrolling through your entire scene switcher time
list and all entries are exactly the same?  end up having some times
different than I saved, sometimes the scene is back to <select scene>, and
transition ends up at <select transition>, and sometimes the day gets
changed. Are you saying that you are unable to duplicate the problem I am
having? I will be happy to add more scenes until it happens again and then
send you the data and the screen shot, it just means screwing up my network
again.

**Comment by WarmUpTill** [comment] 2023-07-09 00:45
>So, you are scrolling through your entire scene switcher time
list and all entries are exactly the same?

I have not compared every single entry - I only checked the ones at the end of the list, as this is what you mentioned in your report.
"Eventually _the bottom of the Time Tab_ of the Advanced Scene Switcher will corrupt and not be what was entered."

Even with close to 1000 entries in the list I am able to reproduce the issue.
So I must be missing some crucial step.

Are you maybe renaming / removing the scenes or transitions?

**Comment by CoreyRosen** [comment] 2023-07-09 00:53
No I am not... I am only setting the times and the scenes and I always use
fade unless I am starting a live show, then I use cut. What would you like
me to do? I cant believe this is only a problem on my OBS.

**Comment by CoreyRosen** [comment] 2023-07-09 09:18
[adv-ss-PBMTV_1080_2.3 2-2023.07.09.02.12.25.txt](https://github.com/WarmUpTill/SceneSwitcher/files/11994842/adv-ss-PBMTV_1080_2.3.2-2023.07.09.02.12.25.txt)
[adv-ss-PBMTV_1080_2.3 2-2023.07.09.02.06.12.txt](https://github.com/WarmUpTill/SceneSwitcher/files/11994843/adv-ss-PBMTV_1080_2.3.2-2023.07.09.02.06.12.txt)
I programmed in the schedule for the overnight. I did not delete any of the old entries. Instead, I added more. I copied the first file after programming in the rest of the schedule throughout tomorrow. (SECOND FILE IN ENTRY) I then closed the advanced scene switcher and reopened it. The second file is what I first recorded. The First File is what was there when I reopened the advanced scene switcher. You will see many of the entries at the bottom of the list are different than the previous file. This keeps happening to me and I cannot find a cause.

**Comment by CoreyRosen** [comment] 2023-07-09 09:35
To be clear, there were only a couple of changes, but I know the more entries I make will just corrupt the playlist more. Apparently, if I keep it open, it doesnt mess up, but it doesnt necessarily play the clips as I programmed them.

**Comment by CoreyRosen** [comment] 2023-07-09 09:36
And I checked my log file and it is completely corrupted. I wouldnt know how to get that to you because it is so big.

**Comment by WarmUpTill** [comment] 2023-07-09 12:37
>What would you like me to do? I cant believe this is only a problem on my OBS.

To be honest I don't know. :(

I am not able to reproduce the issue and the "Time" tab functionality was not touched in years.
I can only suggest to maybe try to use the macro functionality instead.

Maybe the issue is with the size of your scene collection data? (Maybe OBS only supports json files up to a certain size? - just a wild guess)

>You will see many of the entries at the bottom of the list are different than the previous file. This keeps happening to me and I cannot find a cause.

I cannot observe what you are describing.
I only see the following differences in the files you shared:

 * Scene switch to "P - Bumper 0:12 Cryptochronica" on Sunday at 20:06:14 [...] was replaced with "Z - Festival 18" on Saturday at 18:01:37 [...]
 * Scene switch to "Z - Festival 10" on Sunday at 00:42:50 [...] was replaced with "P - Bumper 0:12 Cryptochronica" on Sunday at 20:06:14 [...]
 * Scene switch to "P - Bumper 0:17 Spiderhound" on Monday at 06:08:30 [...] was changed to Sunday.
 * Scene switch to "U - Sunday Morning Cartoons - Calvin and the Colonel - EP01 - 24:55" on Saturday at 18:01:37 [...] was changed to Sunday at 06:08:47 [...]
 * The advanced scene switcher window was resized from 1353 x 641 to 1311 x 643

And these changes are preserved properly even after closing and reopening OBS.

>And I checked my log file and it is completely corrupted.

What do you mean by corrupted?
That seems very unusual.

**Comment by CoreyRosen** [comment] 2023-07-09 17:27
Those changes are the problem. And the more entries I have on the scene
switcher, the larger the changes become. As far as the log file, It does
not record the most recent switch, but something else entirely. Last night,
it showed that it tried to play all the music videos in order one after the
other one every frame. This did not happen because I was monitoring when it
says it did this.

**Comment by WarmUpTill** [comment] 2023-08-28 18:34
I will close this for now as I do not really know how to continue here without being able to reproduce the problem on my end.

In general I would recommend for you to transition to the macro tab, if possible.
It is probably more stable and much more powerful.

**Closed by WarmUpTill** 2023-08-28 18:34 UTC

**Comment by CoreyRosen** [comment] 2023-08-28 19:10
I asked how to do that. Can you please show me how to make the Macro Tab
work for scheduled shows airing at specific times with different lengths
for shows? I will happily use the macro tab, but I have no idea how to
program it.
