### ISSUE TITLE
Hotkeys when not in focus causes video to hang.

### ISSUE THREAD

**Issue by DanielLester83** [WarmUpTill/SceneSwitcher#485] opened 2022-06-26 16:34 UTC
**Describe the bug**
I have noticed that with SceneSwitcher installed and Hotkeys enabled to be active when OBS is not in focus my Nvidia video kernel driver sometimes hangs enough to cause the monitor that OBS is on to flicker. I suspect that the way that SceneSwitcher checks if a hotkey is pressed is delaying or blocking other processes instead of being more asynchronous. The problem seems to go away if you set hotkeys to to not work if OBS is not in focus; so it could be OBS' code. (For reference I am running OBS in administer mode) 

**To Reproduce**
1. Set up a SceneSwitcher Macro with a hotkey
2. Start Recording or Streaming
3. Wait until it happens
4. See either the OBS log or Windows Event Viewer to confirm the problem.

**Expected behavior**
For no lagging to occur

**Comment by WarmUpTill** [comment] 2022-10-04 20:21
I will close this for now as I don't think this issue is caused by the plugin.

**Closed by WarmUpTill** 2022-10-04 20:21 UTC
