### ISSUE TITLE
"Else Action" is still executed when macro is disabled

### ISSUE THREAD

**Issue by dexeonify** [WarmUpTill/SceneSwitcher#992] opened 2024-01-19 16:42 UTC
**Describe the bug**
When a macro is disabled/paused and "Perform actions only on condition changed" is disabled, Advanced Scene Switcher will continue to execute the "else actions" of the macro.

**To Reproduce**
1. Create a "AutoPause" macro
2. Configure the macro so that **if the cursor moves**, it will **unpause** the recording, or else it will **pause** the recording.
3. Untick the AutoPause macro on the left sidebar.
4. Untick Perform actions only on condition changed.
5. Start the recording with Advanced Scene Switcher active.
6. Observe the recording is immediately paused, even if the macro is disabled. If you try to unpause the recording, it will be paused again. I have "Highlight recently performed actions of currently selected macro" enabled, but it didn't reveal the culprit.

**Expected behavior**
No condition or actions should be executed, if the macro is disabled. I've read the wiki on [Macros](https://github.com/WarmUpTill/SceneSwitcher/wiki/Macros#creating-a-new-macro) and [Pausing Macros](https://github.com/WarmUpTill/SceneSwitcher/wiki/Pausing-macros), but I couldn't find anything regarding this special behaviour of "Else actions".

**Logs**
Verbose logging was very spammy, so I've narrowed it down to the relevant sections:
**When recording is started with the macro enabled:**
```log
00:37:43.579: [adv-ss] condition cursor returned 1
00:37:43.579: [adv-ss] Macro AutoPause returned 1
00:37:43.579: [adv-ss] running macro: AutoPause
00:37:43.579: [adv-ss] running actions of AutoPause
00:37:43.579: [adv-ss] performed action "AdvSceneSwitcher.action.recording.type.unpause"
00:37:43.579: [adv-ss] try to sleep for 100
00:37:43.679: [adv-ss] condition cursor returned 0
00:37:43.679: [adv-ss] Macro AutoPause returned 0
00:37:43.679: [adv-ss] running macro: AutoPause
00:37:43.679: [adv-ss] running else actions of AutoPause
00:37:43.679: [adv-ss] performed action "AdvSceneSwitcher.action.recording.type.pause"
00:37:43.679: [adv-ss] try to sleep for 100
00:37:43.680: output adv_file_output paused
```
**When recording is started with the macro disabled:**
```log
00:34:03.500: [adv-ss] Macro AutoPause is paused
00:34:03.501: [adv-ss] running macro: AutoPause
00:34:03.501: [adv-ss] running else actions of AutoPause
00:34:03.501: [adv-ss] performed action "AdvSceneSwitcher.action.recording.type.pause"
00:34:03.501: [adv-ss] try to sleep for 99
```

**Version information**
 - OS: Windows 11
 - OBS Version 30.0.2
 - Plugin Version 1.24.2

**Comment by WarmUpTill** [comment] 2024-01-19 18:58
Thanks for pointing that out! :)
It should be fixed with the linked PR.

A build with a fix will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/7587982595?pr=990

I would appreciate if you could give this a try and report back if the issue is also resolved on your end.
But maybe [Backup your settings](https://github.com/WarmUpTill/SceneSwitcher/wiki/Saving-and-loading-settings#how-to-create-and-import-a-backup-of-your-settings) beforehand just in case.

**Comment by dexeonify** [comment] 2024-01-20 06:48
Yes, everything works as expected now. Thanks for the quick fix!

**Comment by dexeonify** [comment] 2024-01-20 07:06
Actually, I'm going to reopen this because the changes aren't merged yet, and that PR should close this issue anyways.

**A separate but minor issue:**
Is the highlight for "recently executed macros" supposed to be this faint? I'm using the built-in Grey theme, but it happens with the other built-in themes too. I was expecting it to the highlight the _background_ instead of the text. I thought I'd mention it since it's now enabled by default.
![image](https://github.com/WarmUpTill/SceneSwitcher/assets/72267349/90c0531c-e3b0-41c9-9725-869975b676e5)

**Comment by WarmUpTill** [comment] 2024-01-20 13:31
Thanks for the test and confirming that the fix works! :)
I will close the issue once the changes are merged.

>Is the highlight for "recently executed macros" supposed to be this faint?

That is indeed "intended".
I tried flashing the background and that was much worse visually.
So the current solution is just the lesser of two bad solutions.

**Closed** 2024-01-27 13:10 UTC
