### ISSUE TITLE
ADD Automatic Twitch GameName Changer

### ISSUE THREAD

**Issue by cyclemat** [WarmUpTill/SceneSwitcher#330] opened 2021-10-21 18:34 UTC
is it possible to intigrate an function to set the Twitch game section automatic with the scene so when the scene change the game name change ?

i and many friends have on scene per game with backgrount for it so the desktop never show but is was cool when you change to a scene the gamename change on twitch

**Comment by Destroy666x** [comment] 2023-08-16 18:45
Thanks! Things I've noticed so far:
- OBS Studio crashed the first time I tried to request a token and browser said it was redirecting me. I clicked the `Account name` and `Token` unenterable fields beforehand, which was the only difference to when it worked fine the 2nd time
- categories load extremely slowly the 1st time OBS is launch, hanging OBS for 15-20 seconds
- some categories like `Duelyst II` are missing https://www.twitch.tv/directory/game/Duelyst%20II
- - OBS crashed at least once when attempting to switch category (stream was offline)
- `Twtitch typo` in action dropdown

**Comment by Destroy666x** [comment] 2023-08-16 19:11
Actually, the Duelyst II category shows but couldn't be searched the 1st few times I tried. Now search started working. Or it didn't show before maybe, I don't know, I browsed once and didn't notice it at least.

**Comment by WarmUpTill** [comment] 2023-08-16 19:12
Thanks a lot for your tests!

>OBS Studio crashed the first time I tried to request a token and browser said it was redirecting me. I clicked the Account name and Token unenterable fields beforehand, which was the only difference to when it worked fine the 2nd time

>OBS crashed at least once when attempting to switch category (stream was offline)

Can you please share the crash logs?

>categories load extremely slowly the 1st time OBS is launch, hanging OBS for 15-20 seconds

Yeah there is not much I can do here unfortunately :(
That is just how long it takes to fetch all of the games supported by Twitch.
They are cached afterwards, which is why it only takes so long for the first time.

>Twtitch typo in action dropdown

Cheers :)

**Comment by WarmUpTill** [comment] 2023-08-16 19:30
> Which ones are these? If you mean OBS ->Help -> Crahs reports -> crashes folder, I don't see anything there, other than one very old file.

Yeah correct.
What exactly happened when OBS crashed?
Did the program exit on its own? Did the window not react to inputs anymore?

>I see, that's not great job by Twitch API then.

Not really their fault.
There are just too many games :D
Maybe I can add an option to only fetch the top 500 most played games instead of all of them to speed things up.

**Comment by Destroy666x** [comment] 2023-08-16 19:44
> What exactly happened when OBS crashed?

The window closed in the background and I had to relaunch it with "OBS is still running" popup displayed (but only the processes were running, UI wasn't in task bar/tray/anywhere).

> Not really their fault.
There are just too many games :D

I guess, but even for that big of data it's quite slow, I assume it loads also more data than the names? Is it this? https://dev.twitch.tv/docs/api/reference/#search-categories

> Maybe I can add an option to only fetch the top 500 most played games instead of all of them to speed things up.

Or perhaps cross-session cache that you can manuall refresh could work.

**Comment by WarmUpTill** [comment] 2023-08-18 21:58
I reworked the category suggestion to support displaying a dialog which shows the current amount of categories fetched and offers the option to stop fetching more games.

A new build will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/5907294035?pr=823

Let me know what you think!

**Comment by cyclemat** [comment] 2023-08-18 22:15
looks very good that is THE thing good work in the moment i didnt have time to stream so i had testet not in live mode but its looks very good !

**Comment by Destroy666x** [comment] 2023-08-19 02:45
Nice more clear solution :)

The only bad thing now is that not all games are loaded. Again missed Duelyst II when I tested few times.

Also, I livestreamed with previous version for few hours + 2 stream category change actions and had 0 crashes. So I guess they just happened at the start.

**Comment by WarmUpTill** [comment] 2023-08-19 17:46
>Again it missed Duelyst II when I tested few times.

I _think_ the problem is that categories with no viewers are not returned by the "[Get Top Games](https://dev.twitch.tv/docs/api/reference/#get-top-games)" query, which is quite annoying.
I will see if I can find a workround.

**Comment by Destroy666x** [comment] 2023-08-23 15:31
Something seems not right. I can't get search results to display. And search results number went down from 5 to 0 in a matter of minute of trying few times, for "just" keyword.

**Comment by WarmUpTill** [comment] 2023-08-23 17:50
>Unless it adds the found games to the list. But then no idea why it was like 5 -> 3 -> 1 -> 1 -> 0

That is indeed how it works.
It simply adds the new categories to the list.
I probably need to make that more clear.

**Comment by Destroy666x** [comment] 2023-08-23 18:24
Ok, seems to work fine then from what I see, except some cases like mentioned 3 new reported results for the same search which got 5 items before.

**Comment by WarmUpTill** [comment] 2023-08-23 19:09
A new build, which displays another dialog when the search is done and informs that the new results were added to the list, can be found here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/5955422627

>except some cases like mentioned 3 new reported results for the same search which got 5 items before.

I see that as well.
To be honest I am not sure what is causing this.
Maybe it is some race condition on my end that I simply have not found yet.

**Comment by Destroy666x** [comment] 2023-08-23 20:12
Ah ok 👍

**Comment by WarmUpTill** [comment] 2023-08-25 22:50
>except some cases like mentioned 3 new reported results for the same search which got 5 items before.

If I am not misinterpreting my test results, it seems like the `/helix/search/categories` Twitch API simply returns different results for the same query occasionally.
The _amount_ of items returned by the query seems to always stay the same, but order and sometimes the content seem to differ, which leads to the strange behaviour you observed.

So unfortunately there is not much that can be done about that besides searching for the same term multiple times.

---

If no other issues popped up on your end I will merge the changes to the main branch :)

**Closed** 2023-08-26 15:32 UTC

**Comment by WarmUpTill** [comment] 2023-09-06 10:08
I now also added the option to start a commercial.

![image](https://github.com/WarmUpTill/SceneSwitcher/assets/19472752/3337f962-d53a-4e9f-8235-24a6fa59d2ab)

Unfortunately, I am not able to test it as I don't have access to a live partner or affiliate account on Twitch.
Would you be able to test this, in case you have the option to do so?

A build with this feature is available here:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/6064476012

**Comment by Destroy666x** [comment] 2023-09-06 13:10
@WarmUpTill I see that was merged into master, if you could update https://github.com/WarmUpTill/SceneSwitcher/pull/855 with master changes then I'll gladly test!

**Comment by WarmUpTill** [comment] 2023-09-06 19:44
Thanks!

A rebased build of #855 will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/6101694126?pr=855

**Comment by Destroy666x** [comment] 2023-09-06 20:39
@WarmUpTill the duration is in mins, right? Could be labeled better is my small suggestion for now. I'll test if it works on tomorrow's stream

**Comment by WarmUpTill** [comment] 2023-09-07 04:49
>the duration is in mins, right?

It is in seconds.

>Could be labeled better is my small suggestion for now.

Yes, you are right.

**Comment by Destroy666x** [comment] 2023-09-09 02:27
Seemed to work fine for me @WarmUpTill

**Comment by WarmUpTill** [comment] 2023-09-09 05:43
Great!
Thanks a lot for your help in getting this tested!
