### ISSUE TITLE
[Feature Request] Stop action for macros

### ISSUE THREAD

**Issue by darkwolfie37** [WarmUpTill/SceneSwitcher#389] opened 2022-01-12 07:58 UTC
on windows after setting a keybind, the macro will not trigger.

**Comment by darkwolfie37** [comment] 2022-01-12 08:25
Also can we get a hotkey to run the macros plus a action to run other macros?

**Comment by darkwolfie37** [comment] 2022-01-12 21:49
The key binds are made but it won’t run the macro and yes the plug-in is running. Not sure tf is going on

**Comment by WarmUpTill** [comment] 2022-01-13 02:06
Can you please enable verbose logging on the general tab of the plugin, then reproduce the issue, and upload the log file here?

If you need information on how to create and where to find OBS log files have a look at this post.
https://obsproject.com/forum/threads/please-post-a-log-with-your-issue-heres-how.23074/

**Comment by WarmUpTill** [comment] 2022-01-14 04:42
Thank you for the video highlighting and explaining the issue and I apologize for frustrating you - that certainly wasn't my intention.

I will try to replicate your setup and look into this on the weekend / tomorrow after work.

**Comment by darkwolfie37** [comment] 2022-01-14 05:19
alright

**Comment by WarmUpTill** [comment] 2022-01-14 18:46
I have implemented the macro action to stop another macro in the linked PR.
![Stop](https://user-images.githubusercontent.com/19472752/149565984-e840343e-a47e-4d6b-baf0-23d463f5ff01.PNG)
A build will be available here in a few minutes:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/1698915142
(Note that you have to be logged into GitHub to be able to download it)

Let me know if everything works as expected or if you run into issues.

------

If I am not mistaken an alternative approach to achieve what you are looking to do would be the following:
Keep your setup as is but set the following keybinds:
 * Toggle pause of macro Loop1 => F20
 * Toogle pause of macro Loop2 => F20

This should allow you to toggle the activation / deactivation of the loop with a single hotkey while leaving the plugin active.
A small restriction would be however, that, if you should exit OBS while the Loop is still active and reopen OBS, you have to press the hotkey twice to to start the loop.

------

A small note regarding your comment regarding the option "Perform actions only on condition change":
Ticking that box should not make any difference for a condition setup that only consists of a single condition of type "Hotkey".
In general it is only useful for conditions which can be true for a prolonged period of time (e.g. a check for the current scene).
There it might not be desired to continuously run a set of actions but instead only on scene change.

------

Another general remark:
If you start setting up macros I would suggest to move any non-macro tab functions you have set up to the macro tab as well - so in your particular case the "screen region" setup should probably be replaced by a condition of type "Cursor" in combination with an action of type "Switch scene".
The reason being that it will be a lot easier to adjust the control flow if you should expand upon your setup in future.

**Comment by WarmUpTill** [comment] 2022-01-21 17:50
I will merge these changes and close this issue - please let me know if you should run into any issues

**Closed by WarmUpTill** 2022-01-21 17:51 UTC
