### ISSUE TITLE
Audio "Set source volume" setting the wrong volume and fading too fast

### ISSUE THREAD

**Issue by timonsku** [WarmUpTill/SceneSwitcher#769] opened 2023-06-04 19:39 UTC
**Describe the bug**
I have set a timer macro that triggers on a certain time each day and then does two action where it fades one audio source to volume 0% and the other to 30% but no matter what I set for the one that is supposed to 30% it always fades to around 60-70% and does so in a matter of a few seconds despite having it set to 60 seconds. As if there is some default value being used instead of the user provided values.

This is what it always sets it too, no matter what value I enter.
![grafik](https://github.com/WarmUpTill/SceneSwitcher/assets/2370185/1c7878f6-54d2-4258-a1c7-35535af31569)

**To Reproduce**

Setup two media sources with audio files and setup the following macro:
![grafik](https://github.com/WarmUpTill/SceneSwitcher/assets/2370185/5c5cd35a-6261-462d-9834-a24b896b0ecf)

**Expected behaviour**
My audio should fade in the set time to the set volume percentage.

**Logs**
Snippet from running a macro manually which causes the described behaviour.
```
21:35:58.683: [adv-ss] Macro Day returned 0
21:35:58.685: [adv-ss] try to sleep for 298
21:35:58.983: [adv-ss] condition date returned 0
21:35:58.983: [adv-ss] Macro Night returned 0
21:35:58.983: [adv-ss] condition date returned 0
21:35:58.983: [adv-ss] Macro Day returned 0
21:35:58.985: [adv-ss] try to sleep for 298
21:35:59.061: [adv-ss] performed action "AdvSceneSwitcher.action.filter.type.disable" for filter "Apply LUT" on source "Camlink"
21:35:59.062: [adv-ss] performed action "AdvSceneSwitcher.action.filter.type.disable" for filter "Color Correction Day" on source "Camlink"
21:35:59.062: [adv-ss] performed action "AdvSceneSwitcher.action.filter.type.enable" for filter "Color Correction Night" on source "Camlink"
21:35:59.062: [adv-ss] performed action "AdvSceneSwitcher.action.filter.type.enable" for filter "Sharpen" on source "Camlink"
21:35:59.062: [adv-ss] performed action "AdvSceneSwitcher.action.audio.type.sourceVolume" for source "Day Sounds" with volume 0 with fade 1 60.000000
21:35:59.062: [adv-ss] performed action "AdvSceneSwitcher.action.audio.type.sourceVolume" for source "Night Sounds" with volume 30 with fade 1 60.000000
21:35:59.283: [adv-ss] condition date returned 0
21:35:59.283: [adv-ss] Macro Night returned 0
21:35:59.283: [adv-ss] condition date returned 0
21:35:59.283: [adv-ss] Macro Day returned 0
21:35:59.284: [adv-ss] try to sleep for 299
21:35:59.584: [adv-ss] condition date returned 0
21:35:59.584: [adv-ss] Macro Night returned 0
21:35:59.584: [adv-ss] condition date returned 0
21:35:59.584: [adv-ss] Macro Day returned 0
21:35:59.587: [adv-ss] try to sleep for 296
21:35:59.883: [adv-ss] condition date returned 0
```

**Version information**
 - OS: Windows 11
 - OBS Version 29.1.1
 - Plugin Version 1.22.1

**Comment by WarmUpTill** [comment] 2023-06-05 18:47
>My audio should fade in the set time to the set volume percentage.

Unfortunately I am not able to reproduce these timing issues.

Can you maybe check the "Wait for fade to complete." boxes for testing purposes and record another log so I can see when each fade takes place (Maybe also add a dummy action after the last fade as well so there is a final log indicating the end of the execution of the macro)

>no matter what I set for the one that is supposed to 30% it always fades to around 60-70% 

`-10.6 db` seems to be about the expected value for `30%` volume.

I apologize if I am stating something that is obvious to you already:
Note that [decibel is a logarithmic scale](https://en.wikipedia.org/wiki/Decibel).
This is the slider moves a comparatively large amount when moving from `0%` to `1%` volume compared to when changing the volume from `50%` to `51%`.

**Comment by timonsku** [comment] 2023-06-06 03:36
Oh okay I expected it would set it in relation to the slider position, not in db scale.
Though even then I should see a difference, setting it to 5% yields the same result.
Only 0% makes a difference and sets it to fully mute.

Will try to make a log capture like you described.

**Comment by WarmUpTill** [comment] 2023-06-06 18:11
>Though even then I should see a difference, setting it to 5% yields the same result.

That seems really strange indeed.
Is there maybe a conflicting audio action that sets the volume of the same source?

**Comment by WarmUpTill** [comment] 2023-08-28 18:36
I will close this for now.
Feel free to re-open once you have the log file! :)

**Closed by WarmUpTill** 2023-08-28 18:36 UTC

**Comment by timonsku** [comment] 2023-08-28 19:58
Ah sorry, I think the wait for complete flag had fixed it plus setting a very low volume as target
