### ISSUE TITLE
[feature request] Add an action to change stream info, including e.g. title and category

### ISSUE THREAD

**Issue by Destroy666x** [WarmUpTill/SceneSwitcher#787] opened 2023-07-11 14:36 UTC
**Is your feature request related to a problem? Please describe.**
The only way to automatically change stream title, category, etc. would be with a HTTP request, currently.

**Describe the solution you'd like**
It would be nice if the plugin integrated with OBS account and allowed an action that changes stream info like title, category, etc. 

**Describe alternatives you've considered**
The only one I see is the mentioned HTTP request.

**Comment by WarmUpTill** [comment] 2023-08-16 15:31
A first build with the requested functionality is available here:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/5880188307?pr=823

Closing this as a duplicate of https://github.com/WarmUpTill/SceneSwitcher/issues/330.
Please give feedback in the other issue if everything works as expected :)

**Closed by WarmUpTill** 2023-08-16 15:31 UTC
