### ISSUE TITLE
Not showing up in OBS Tools (WIndows 64 bit)

### ISSUE THREAD

**Issue by azzyzalea** [WarmUpTill/SceneSwitcher#1020] opened 2024-02-13 23:10 UTC
I know that this issue has popped up for others (Mac and Linux users), but now I am having the same issue. I've installed the Advanced Scene Switcher 5+ times trying to get it to work, but it does not pop up in the Tools menu. I have tried downloading it just from the "Download" menu, I've tried taking it from the Zip files, and I've tried downloading it from the Desktop. I've also tried redownloading the AdvSS Installer to see if that worked. It still refuses to show up.

1. Redownloaded Advanced Scene Switcher
2. Run it to install
3. Click "Finish" when it's done installing

I'm not sure what I'm doing wrong as I've _never_ had this problem before last week (Feb 8th, 2024). 
I'm not expecting a response, I just want to let you guys know what is going on. If I could get a response, that'd be great. However, I would prefer you guys know what's going on and hopefully get a fix for it whenever you can.

**Version information**
 - OS: Windows 10
 - OBS Version: 30.0.2
 - Plugin Version: 1.24.2

**Comment by WarmUpTill** [comment] 2024-02-14 15:44
Can you share a log file?
This should indicate if it is a problem of the files not being at the right place or something else.

Other ideas:
* Maybe you have multiple copies of OBS installed?
* Was the obs-studio folder moved to a different location after it was installed?

**Comment by WarmUpTill** [comment] 2024-02-14 20:50
So the log does not show any indication of OBS attempting to load files related to the advanced scene switcher.
That would lead me to believe that the files are in the wrong place.

>I did move it, but that was with a reinstallation of OBS. I had uninstalled it and reinstalled the updated version on my main drive.

That _could_ explain it, as now the installer might be placing the files at the old location.

I would suggest that you try the following:
* Right click the shortcut you use to start OBS
* Click "Open file location"
* Continue to do this on the resulting OBS shortcuts until you end up in the folder containing obs64.exe
* Move two folders "up" so your explorer window is the folder named "obs-studio".
* Extract the contents of "advanced-scene-switcher-windows-x64.zip" into this folder.

If you don't manage to get it working feel free to send me a DM on the forums so we can set up a quick call and I will walk you through it / we can figure out what the issue is.

**Comment by WarmUpTill** [comment] 2024-02-25 12:19
I will close this for now.
Let me know if you need further support! :)

**Closed by WarmUpTill** 2024-02-25 12:19 UTC

**Comment by azzyzalea** [comment] 2024-02-26 19:32
I COMPLETELY forgot to reply to this, I'm so sorry! It ended up working, thank you again!
     On Sunday, February 25, 2024 at 06:20:03 AM CST, WarmUpTill ***@***.***> wrote:  
 
 


I will close this for now.
Let me know if you need further support! :)
